#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

function usage() {
  console.error("Usage: node build_zotero_linked_attachment_js.mjs <mapping.json> <output.js>");
  process.exit(2);
}

function defaultContentType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".pdf") return "application/pdf";
  if (ext === ".md" || ext === ".markdown") return "text/markdown";
  if (ext === ".txt") return "text/plain";
  return "application/octet-stream";
}

function normalizeRows(rawRows) {
  if (!Array.isArray(rawRows)) {
    throw new Error("Mapping JSON must be an array");
  }
  return rawRows.map((row, index) => {
    if (!row || typeof row !== "object") {
      throw new Error(`Row ${index} must be an object`);
    }
    if (!row.parentKey) {
      throw new Error(`Row ${index} is missing parentKey`);
    }
    if (!row.path) {
      throw new Error(`Row ${index} is missing path`);
    }
    return {
      parentKey: String(row.parentKey),
      path: String(row.path),
      title: row.title ? String(row.title) : path.basename(String(row.path)),
      contentType: row.contentType ? String(row.contentType) : defaultContentType(String(row.path)),
      tags: Array.isArray(row.tags) ? row.tags.map(String) : [],
    };
  });
}

const [mappingPath, outputPath] = process.argv.slice(2);
if (!mappingPath || !outputPath) usage();

const rows = normalizeRows(JSON.parse(fs.readFileSync(mappingPath, "utf8")));

const zoteroScript = `// Generated by zotero-linked-attachments.
// Run inside Zotero Desktop: Tools -> Developer -> Run JavaScript.
// Check "Run as async function" before executing.

const rows = ${JSON.stringify(rows, null, 2)};
const libraryID = Zotero.Libraries.userLibraryID;
const result = {
  createdCount: 0,
  skippedCount: 0,
  missingParents: [],
  errors: [],
  created: [],
  skipped: [],
};

for (const row of rows) {
  try {
    const parent = Zotero.Items.getByLibraryAndKey(libraryID, row.parentKey);
    if (!parent) {
      result.missingParents.push(row.parentKey);
      continue;
    }

    const childIDs = parent.getAttachments();
    const existing = childIDs
      .map((id) => Zotero.Items.get(id))
      .find((item) => item && item.attachmentPath === row.path);

    if (existing) {
      result.skippedCount++;
      result.skipped.push({
        parentKey: row.parentKey,
        attachmentKey: existing.key,
        reason: "same-path attachment exists",
      });
      continue;
    }

    const attachment = await Zotero.Attachments.linkFromFile({
      file: row.path,
      parentItemID: parent.id,
      contentType: row.contentType,
    });

    if (row.title) {
      attachment.setField("title", row.title);
    }
    for (const tag of row.tags || []) {
      attachment.addTag(tag);
    }
    await attachment.saveTx();

    result.createdCount++;
    result.created.push({
      parentKey: row.parentKey,
      attachmentKey: attachment.key,
      path: row.path,
      contentType: row.contentType,
    });
  } catch (error) {
    result.errors.push({
      parentKey: row.parentKey,
      path: row.path,
      message: String(error && error.message ? error.message : error),
    });
  }
}

return JSON.stringify(result, null, 2);
`;

fs.writeFileSync(outputPath, zoteroScript, "utf8");
console.log(JSON.stringify({ rows: rows.length, outputPath }, null, 2));
